import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.nav}>
        Navbar
        </div>
        <div className={styles.topBackground}/>
        <div className={styles.inputCard}>
          <input className={styles.input}/>
          <button className={styles.button}>Send</button>
        </div>
        <div className={styles.grid}>
          <div className={styles.content}/>
        </div>
      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}
